export function mapRow(row) {
  return {
    event: {
      title: row.title || null,
      start_date: row.startDate || null,
      start_time: row.startTime || null,
      end_date: row.endDate || null,
      end_time: row.endTime || null,
      description: row.description || null,
      venue: row.venue || null,
      address: row.address || null,
      city: row.city || null,
      state: row.state || null,
      zip: row.zip || null,
      latitude: null,
      longitude: null,
      category: null,
      tags: row.tags || null,
      price: row.price || null,
      image_url: row.imageUrl || null,
      url: row.externalUrl || null,
      external_url: row.externalUrl || null,
      contact: null,
      organizer: row.organizer || "North Suburban Library District",
      is_online: row.isOnline === "yes" ? 1 : 0,
      recurring: 0,
      recurrence_frequency: null,
      recurrence_end_date: null,
    },
    sourceId: row.sourceId || null,
    sourceUrl: row.externalUrl || null,
  };
}
